module.exports = {
    CONFIG_FILE : "config.db",
    TRACKS_FILE : "tracks.db",
    SPOTIFY_CONFIG : "spotifyconfig",
    CONFIG : "config",
    AUTH: "auth",
    ADMIN: "admin",
    NAME: "name",
    SETTINGS : "settings",
    SEARCH : "search",
    HISTORY: "history",
    PLAYLIST: "playlist",
    TRIGGER_ID : 'trigger_id',
    TRACK_URI: 'track_uri',
    SCOPES : ['user-read-recently-played',
        'user-read-playback-state',
        'user-modify-playback-state',
        'playlist-read-collaborative',
        'playlist-read-private',
        'playlist-modify-public',
        'playlist-modify-private',
        'streaming'],
    SEE_MORE_TRACKS : "SEEMORETRACKS",
    SEE_MORE_ARTISTS: "SEEMOREARTISTS",
    ADD_SONG : "ADDSONG",
    CRONJOB1 : "CRONJOB1",
    CRONJOB2 : "CRONJOB2",
    SKIP: "skip",
    CURRENT_TRACK : "current_track",
    AFRICA: "spotify:track:2374M0fQpWi3dLnB54qaLX",
    RESET: "reset",
    ARTIST: "artist",
    BLACKLIST : "blacklist",
    BLACKLIST_REMOVE: "blacklist_remove"
}