module.exports = {
    CONFIG_FILE : "config.db",
    TRACKS_FILE : "tracks.db",
    SPOTIFY_CONFIG : "spotifyconfig",
    CONFIG : "config",
    AUTH: "auth",
    ADMIN: "admin",
    NAME: "name",
    SETTINGS : "settings",
    TRACK : "track",
    HISTORY: "history",
    PLAYLIST: "playlist",
    TRIGGER_ID : 'trigger_id',
    TRACK_URI: 'track_uri',
    SCOPES : ['user-read-recently-played',
        'user-read-playback-state',
        'user-modify-playback-state',
        'playlist-read-collaborative',
        'playlist-read-private',
        'playlist-modify-public',
        'playlist-modify-private',
        'streaming'],
    SEE_MORE_TRACKS : "SEEMORETRACKS",
    ADD_SONG : "ADDSONG",
    CRONJOB1 : "CRONJOB1",
    CRONJOB2 : "CRONJOB2",
    SKIP: "skip"
}